### ISSUE TITLE
Nothing is imported

### ISSUE THREAD

**Issue by agross** [nafets227/finance#7] opened 2020-01-25 00:14 UTC
Hi,

thank you for creating this project. I'm currently trying to get this running. The account setup seems to work and local files are created, but after aqbanking is done nothing is imported into the DB.

```
...
app_1  | Processing transactions and balances
app_1  | /usr/local/bin/finance-entrypoint: line 599: /finance/inbound.aqb-tran/*: No such file or directory
app_1  | Importing transactions and balances into database
app_1  | Importing directory /finance/inbound.aqb6
app_1  | Not importing unknown type aqb6 in /finance/inbound.aqb6/20200124-234818.541173768
app_1  | Importing directory /finance/inbound.aqb6-bal
app_1  | Importing directory /finance/inbound.aqb6-tran
```

Specifically the files in /finance/inbound.aqb6/ contain balances and transactions, but the script does not consider them. Any idea how I can resolve this?

**Comment by nafets227** [comment] 2020-01-25 08:43
HI,

thanks for reporting. Indeed I must admit that this behaviour is expected in 0.5ALHPA2 (that is also the actual git master).

The Import logic for aqbanking 5.x does not work with aqbanking 6.x, it needs to be adopted.

I released 0.5ALPHA though to allow collecting data. knowing also that currenctly only last 90 days can be imported from Banks (PSD2) without strong authentification. This ia another Topic I Need to work on (dont know yet if and how aqbanking supports SMS Tan that I am using).

So for 0.5 there are following items to be solved:
- Strong Authentication to allow retrieving data more than 90 days ago
- Importing aqb6
- Importing aqb5 data that might be existing (e.g. in --rescan)

Any help is more than welcome, since I am doing this Project in my private spare time.

**Comment by agross** [comment] 2020-01-25 10:51
Hi @nafets227,

Thanks for replying. I was trying the previous release after reporting here, but 0.4.1 does not work for my bank account. I believe this is due to aqbanking being too old (pre-PSD2?).

I personally have no requirement to import data > 90 days (have that cached already), so a solution that queries recent transactions is fine with me.

**Comment by nafets227** [comment] 2020-01-25 11:09
Yes, I can confirm 0.4.1 includes aqbanking5 That is not working anymore since PSD2 on 15.9.2019. Aqbanking6 has been released in January 2020.

Thanks for your input, will prioritize aqb6 import for next alpha or beta version, but it might take me some weeks.

**Comment by agross** [comment] 2020-01-25 11:28
Please let me know if/how I can help or test!

**Comment by nafets227** [comment] 2020-01-26 21:45
Implemented in master branch, not released yet.
Happy if you could test it, I didnt test much yet.
Special Attention should be taken to the "Verwendungszweck" / Purpose field(s).

Take care, do NOT use it in production!

**Comment by agross** [comment] 2020-01-26 23:34
Thanks you for providing something to test. I tried to create a new docker image from master (`docker build .`) but that failed:

```
Step 19/36 : RUN 	cd /home/jenkins/fntxt2sql && 	make
...
gcc -pipe -Wall -DCONF_MYSQL -DCONF_HBCIPX -DCONF_AQB6 -I/usr/include/aqbanking6 -I/usr/include/gwenhywfar5 -g -pg -DDEBUG -DVERSION="\"\"" -o fntxt2sql-aqb6.o -c fntxt2sql-aqb6.c
fntxt2sql-aqb6.c:10:10: fatal error: aqbanking6/aqbanking/banking.h: No such file or directory
   10 | #include <aqbanking6/aqbanking/banking.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:92: fntxt2sql-aqb6.o] Error 1
```

I kindly suggest you resume work on a separate git branch and let Docker Hub assign a tag based on the branch name. Then Docker Hub will do the build, leaving out any specialties from my and your machine.

**Comment by nafets227** [comment] 2020-01-28 21:44
Thx, the error was a leftover of local build being copied into the container, omitting the build in container on my machine. Fixed.

On Top I also got Import with aqb6 running. 

If docker build succeeds for Tag "latest" (automatically scheduled by my push just a few mins ago) I hope you can test.

**Comment by agross** [comment] 2020-01-29 11:30
I'd say it looks pretty neat except for some stray newlines in the Verwendungszweck ;-)

```
MariaDB [finance]> select datum, betrag, part_name1, VZWECK1  from fn_entry order by datum desc limit 20;
+------------+-----------+-----------------------------+-----------------------------------------------------+
| datum      | betrag    | part_name1                  | VZWECK1                                             |
+------------+-----------+-----------------------------+-----------------------------------------------------+
| 2020-01-27 |      0.00 | NULL                        | NULL                                                |
| 2020-01-25 |   1550.88 | NULL                        | NULL                                                |
| 2020-01-25 |   2500.55 | NULL                        | NULL                                                |
| 2020-01-22 |    -92.55 | DB Vertrieb GmbH            | Fahrschein CM7NOT                                   |
| 2020-01-22 |    -48.45 | DB Vertrieb GmbH            | Fahrschein 1PSS4Q                                   |
| 2020-01-22 |    -48.45 | DB Vertrieb GmbH            | Fahrschein 3WZYZ1                                   |
| 2020-01-17 |    -10.00 | NULL                        | Jahresgebuehr KreditkarteKa
rte: 537505XXXXXX   |
| 2020-01-17 |    -10.00 | NULL                        | Jahresgebuehr KreditkarteKa
rte: 537505XXXXXX   |
| 2020-01-13 |   -300.00 | EDV-Dienstleistungen        | Rechnung 2020/001,Innergeme
inschaftliche Leistung, |
| 2020-01-10 | -17595.64 | Foobar Software             | Rechnung R2019/060                                  |
| 2020-01-10 |  13002.37 | xxxxxxxxxxxxxxxxxxxxxxxxxxx | Umbuchung                                           |
| 2020-01-09 |   -222.00 | xxxxxxxxxxx                 | Erstattung Auslagen xxxx xx
xxxx,xxxx           |
| 2020-01-09 |  -1438.22 | Finanzamt xxxxxxxxxx        | xxx/xxx/xxxxxx Umsatzsteuer
11-2019                 |
| 2020-01-07 |   -103.00 | DB Vertrieb GmbH            | Fahrschein A2ADNE                                   |
| 2020-01-06 |    -12.95 | DB Vertrieb GmbH            | Fahrschein FVA4E1                                   |
| 2020-01-06 |    -12.95 | DB Vertrieb GmbH            | Fahrschein NFN4F7                                   |
| 2020-01-02 |  -3570.00 | Marcel xxxxx                | Rechnung R00003                                     |
| 2020-01-02 |  -2261.00 | xxx xxxxxxxxxx GmbH   Co. K | Rechnung xxxxxxxxxx-R05-19121
9                       |
| 2020-01-02 |   -505.75 | xxxxxxxxx xxxxxx            | Rechnung 9/2019                                     |
| 2020-01-02 |    -87.85 | xxxxxxxxxxxxx.de xxxxxxxxxx | MDT xxxxx RE 128667                                 |
+------------+-----------+-----------------------------+-----------------------------------------------------+
```

The first three rows are not actual transactions, though. The second and third row's values are the same as in `fn_entry_balance`. Not sure if this is expected.

```
MariaDB [finance]> select * from fn_entry_balance;
+------------+------+-------+------------+-----------+-----------------+
| ORIG_KTONR | JAHR | MONAT | SALDO_DAY  | SALDO     | saldo_corrected |
+------------+------+-------+------------+-----------+-----------------+
| 0001708123 | 2019 |    10 | 2019-10-31 |  -5559.73 |        -5559.73 |
| 0001708123 | 2019 |    11 | 2019-11-29 |  -7453.40 |        -7453.40 |
| 0001708123 | 2019 |    12 | 2019-12-30 | -11298.71 |       -11298.71 |
| 0001708123 | 2020 |     1 | 2020-01-25 |   2500.55 |         2500.55 |
| 0009679456 | 2019 |    11 | 2019-11-26 |  -6395.44 |        -6395.44 |
| 0009679456 | 2019 |    12 | 2019-12-30 |  -6475.80 |        -6475.80 |
| 0009679456 | 2020 |     1 | 2020-01-25 |   1550.88 |         1550.88 |
+------------+------+-------+------------+-----------+-----------------+
```

**Comment by nafets227** [comment] 2020-01-29 19:39
database entries seem correct, please have alook into the column "BUCHART". A value of "E" indicates a "Saldo", a value of "B" is a real transaction. All other database Elements are defined as views on fn_entry.

Checking about newlines my bank HVB is really sending them as "%0A" (please check in the aqbanking context file in store.aqb6 directory if this is also true for your bank; search for "purpose"). Don´t know what´s best way to handle them? I could
1. Leave newlines as is (this is what the software currently does)
1. Use newlines as field separator, filling VZWECK1, VZWECK2, ... But what if there are more separators than VZWECK fields? What if the text is between two Separators is longer than 27 characters (limit of VZWECK2-7 coming from old BTX/HBCI)
1. ignore any newlines and delete them from the string before storing in the DB

Any suggestions?

**Comment by agross** [comment] 2020-01-29 21:18
> database entries seem correct, please have a look into the column "BUCHART". A value of "E" indicates a "Saldo", a value of "B" is a real transaction.

Yep, I can confirm that this is the case.

> Checking about newlines my bank HVB is really sending them as "%0A" 

Yes, my purposes contain `%0A` as well. It seems my bank (netbank) inserts them. I can handle that in code, so please leave them as-is.

--- 

Anything else I should confirm?

**Comment by nafets227** [comment] 2020-01-29 21:49
Thank you for testing
Feel free to use 0.5-beta1 just released. It is identical to the version you tested.

**Comment by agross** [comment] 2020-01-29 21:50
Many thanks!

**Closed by nafets227** 2020-01-29 21:49 UTC
